name: movies_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  random_avatar: ^0.0.8
  animated_toggle_switch: ^0.8.3
  country_flags: ^3.0.0
  retrofit: ^4.4.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  supabase_flutter: ^2.8.1
  fluttertoast: ^8.2.8
  lottie: ^3.1.3
  injectable: ^2.5.0
  get_it: ^8.0.2
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.6.2
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  build_runner: ^2.4.13


flutter:
  assets:
    - assets/images/
    - assets/images/actor.png
    - assets/images/teeest.jpg
  uses-material-design: true

